databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "0"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DJANGO_ALLOWED_HOST
  scope: RUN_AND_BUILD_TIME
  value: .ondigitalocean.app
- key: DJANGO_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  value: abc123
- key: DJANGO_SUPERUSER_EMAIL
  scope: RUN_AND_BUILD_TIME
  value: khbharathofficial@gmail.com
- key: DJANGO_SUPERUSER_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: khbharath
- key: DJANGO_SUPERUSER_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: abc0123
- key: POSTGRES_DB
  scope: RUN_AND_BUILD_TIME
  value: ${db.DATABASE}
- key: POSTGRES_HOST
  scope: RUN_AND_BUILD_TIME
  value: ${db.HOSTNAME}
- key: POSTGRES_USER
  scope: RUN_AND_BUILD_TIME
  value: ${db.USERNAME}
- key: POSTGRES_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ${db.PASSWORD}
- key: POSTGRES_PORT
  scope: RUN_AND_BUILD_TIME
  value: ${db.PORT}
- key: AWS_ACCESS_KEY_ID
  scope: RUN_AND_BUILD_TIME
  value: abc0123
- key: AWS_SECRET_ACCESS_KEY
  scope: RUN_AND_BUILD_TIME
  value: abc0123
- key: AWS_STORAGE_BUCKET_NAME
  scope: RUN_AND_BUILD_TIME
  value: trydjangoo
jobs:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: bharathkumarkh/Try-Django-
  instance_count: 2
  instance_size_slug: professional-xs
  kind: PRE_DEPLOY
  name: django-migrate-job
  run_command: |
    python manage.py migrate --noinput
  source_dir: /
name: try-django-3-2
region: blr
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: bharathkumarkh/Try-Django-
  http_port: 8080
  instance_count: 2
  instance_size_slug: professional-xs
  name: try-django-3-2
  routes:
  - path: /
  run_command: |
    gunicorn --worker-tmp-dir /dev/shm trydjango.wsgi
  source_dir: /
