# Generated by Django 3.2.13 on 2022-07-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeingredientimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeIngredientImage',
        ),
    ]
